name: ArcadeFrame
description: An app to easily play and manage CarolinaIgnites games.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# For evey subsequent release, increment the build number. So you might have
# something that looks like 5.3.8+203
version: 1.0.2+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Builtin
  async:
  http:
  path_provider:
  # Webview
  webview_flutter: ^0.3.7
  #DB
  sqflite: any
  # File processing
  reflected_mustache: ^1.0.11
  flutter_markdown: ^0.3.5
  # Analytics
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.11
  # Share
  share: ^0.6.4
  # UI
  flare_flutter:
  # Game services
  games_services: ^0.2.6
  # QR code
  uni_links:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

  assets:
    - assets/icons/gamepad.png
    - assets/icons/heart.flr
    - assets/card.png
    - assets/colors.png
    - assets/the.stache.js
    - assets/game/game.html
    - assets/game/css/arcadeframe.css
    - assets/game/css/gameframe.css
    - assets/game/css/minimal.css
    - assets/game/js/gameframe.js
    - assets/game/js/interactive-custom.js
    - assets/game/js/nipplejs.js
    - assets/game/js/physicsjs-full.min.js
    # Pages
    - assets/pages/about.md
    - assets/pages/faq.md
    - assets/pages/legal.md
    - assets/pages/privacy.md
    - assets/pages/license.md

  fonts:
    - family: arcadeclassic
      fonts:
       - asset: assets/fonts/arcadeclassic.ttf
    - family: Halo
      fonts:
       - asset: assets/fonts/halo.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
